[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cesm"
version = "0.1.0"
dependencies = [
    "linkml-runtime",
    "pyyaml",
]

[tool.setuptools.packages.find]
where = ["src"]